"""
Custom Fields Manager - Manages Jira custom fields for test case display
Creates and updates custom fields to show generated test cases
"""

import logging
import json
import base64
import urllib.request
import urllib.error
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class CustomFieldsManager:
    """Manages Jira custom fields for test case integration"""

    def __init__(self, jira_base_url: str, email: str, api_token: str):
        """Initialize custom fields manager"""
        self.base_url = jira_base_url.rstrip('/')
        self.email = email
        self.api_token = api_token
        self.custom_field_id = None

    def _make_request(self, method: str, endpoint: str, payload: Optional[Dict] = None) -> tuple:
        """Make HTTP request to Jira API"""
        url = f"{self.base_url}/rest/api/3{endpoint}"
        credentials = f"{self.email}:{self.api_token}"
        encoded = base64.b64encode(credentials.encode()).decode()

        headers = {
            'Authorization': f'Basic {encoded}',
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        }

        try:
            if method in ['POST', 'PUT']:
                data = json.dumps(payload).encode('utf-8') if payload else None
                req = urllib.request.Request(url, data=data, headers=headers, method=method)
            else:
                req = urllib.request.Request(url, headers=headers, method=method)

            with urllib.request.urlopen(req, timeout=10) as response:
                body = response.read().decode('utf-8')
                result = json.loads(body) if body else {}
                return response.status, result
        except urllib.error.HTTPError as e:
            error_body = e.read().decode('utf-8')
            try:
                error_data = json.loads(error_body)
            except:
                error_data = {"error": error_body}
            logger.error(f"{method} {endpoint} → {e.code}: {error_data}")
            return e.code, error_data
        except Exception as e:
            logger.error(f"Request failed ({method} {endpoint}): {e}")
            return 500, {"error": str(e)}

    def get_or_create_custom_field(self) -> Optional[str]:
        """Get or create 'Inhouse TC Generator' custom field"""
        try:
            # First, try to find existing custom field
            status, fields_data = self._make_request('GET', '/fields')

            if status == 200:
                fields = fields_data if isinstance(fields_data, list) else []
                for field in fields:
                    if field.get('name') == 'Inhouse TC Generator':
                        self.custom_field_id = field.get('id')
                        logger.info(f"✓ Found existing custom field: {self.custom_field_id}")
                        return self.custom_field_id

            # If not found, create it
            logger.info("⚠️ Custom field not found, attempting to create...")

            create_payload = {
                "name": "Inhouse TC Generator",
                "description": "Test cases generated by Inhouse TC Generator plugin",
                "type": "com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield",
                "searcherKey": "com.atlassian.jira.plugin.system.customfieldtypes:textsearcher"
            }

            status, response = self._make_request('POST', '/fields', create_payload)

            if status == 201:
                self.custom_field_id = response.get('id')
                logger.info(f"✓ Created custom field: {self.custom_field_id}")
                return self.custom_field_id
            else:
                logger.warning(f"Could not create custom field: {response}")
                return None

        except Exception as e:
            logger.error(f"Error managing custom field: {e}")
            return None

    def update_issue_with_test_cases(self, issue_key: str, test_cases: List[Dict]) -> bool:
        """Update issue with generated test case information"""
        try:
            if not self.custom_field_id:
                logger.warning(f"Custom field ID not set, skipping update for {issue_key}")
                return False

            # Format test cases for display
            tc_lines = []
            for tc in test_cases:
                key = tc.get('key', 'N/A')
                qc_num = tc.get('qc_number', 'N/A')
                status = tc.get('status', 'synced')
                tc_lines.append(f"• [{qc_num}] [~{key}] - {status}")

            display_text = "Generated Test Cases:\n" + "\n".join(tc_lines)

            # Update the custom field
            payload = {
                "fields": {
                    self.custom_field_id: display_text
                }
            }

            status, response = self._make_request('PUT', f'/issues/{issue_key}', payload)

            if status == 204:
                logger.info(f"✓ Updated {issue_key} with test cases")
                return True
            else:
                logger.warning(f"Failed to update {issue_key}: {response}")
                return False

        except Exception as e:
            logger.error(f"Error updating issue with test cases: {e}")
            return False

    def add_test_case_to_issue(self, parent_key: str, test_case_key: str, qc_number: str) -> bool:
        """Add single test case to issue's custom field"""
        try:
            if not self.custom_field_id:
                logger.warning("Custom field ID not set")
                return False

            # Get current field value
            status, issue_data = self._make_request('GET', f'/issues/{parent_key}?fields={self.custom_field_id}')

            if status != 200:
                logger.warning(f"Could not fetch {parent_key}")
                return False

            current_value = issue_data.get('fields', {}).get(self.custom_field_id, '')

            # Append new test case
            new_entry = f"• [{qc_number}] [~{test_case_key}]"

            if current_value:
                updated_value = f"{current_value}\n{new_entry}"
            else:
                updated_value = f"Generated Test Cases:\n{new_entry}"

            # Update field
            payload = {
                "fields": {
                    self.custom_field_id: updated_value
                }
            }

            status, response = self._make_request('PUT', f'/issues/{parent_key}', payload)

            if status == 204:
                logger.info(f"✓ Added {test_case_key} to {parent_key}")
                return True
            else:
                logger.warning(f"Failed to add test case: {response}")
                return False

        except Exception as e:
            logger.error(f"Error adding test case to issue: {e}")
            return False
